### PR TITLE
bump easy-plugin version

### PR DESCRIPTION
**Pull request by KyleMayes**
Hello, I'm the developer of `easy-plugin`. I pushed an update today that made some breaking changes, this pull request fixes them in your project. The impact ended up being very small, but I decided to make the pull request anyway. :)

### CODE REVIEW

**Comment by hansihe** [comment]
Thank you for the pull request!

**Comment by hansihe** [comment]
Published version 0.7.2 of rustler-codegen with the changes.

**Comment by hansihe** [comment]
@KyleMayes While I have you here, it would be nice to get your express permission change the license to MIT/Apache dual license in the future.

**Comment by KyleMayes** [comment]
Sure, go ahead.

**Pull request merged**
