### PR TITLE
bump erlang_nif-sys to 0.6.3

### LINKED ISSUE #115: ERTS 9.2 not supported

### PR DESCRIPTION
**Pull request by evnu**
This enables support for otp-20.2.2 and fixes #115.

### CODE REVIEW

**Comment by evnu** [comment]
Note that the patch version of rustler should be increased accordingly.

**Comment by scrogson** [comment]
@evnu thanks for the PR! Can you rebase this on `master` and bump `otp_release` to `20.2.2` in the `.travis.yml` so we can verify this change?

**Comment by evnu** [comment]
@scrogson rebased and added `otp_release`.

**Comment by scrogson** [comment]
🤘❤️

**Comment by tcitworld** [comment]
Can this be released ?

**Comment by OvermindDL1** [comment]
One of my bots is very dead due to upstream libraries using this and no new release has been released with this support?  ^.^

(Working around it temporarily via a direct github dependency, does not work since the base root of this project is not a mix project...)

**Comment by scrogson** [comment]
@OvermindDL1 you can use the `sparse` option:

```ex
{:rustler, github: "hansihe/rustler", sparse: "rustler_mix"}
```

**Comment by hansihe** [comment]
No worries though, I will get off my ass and do a release right now.

**Comment by hansihe** [comment]
New release `0.16.0` has been published.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 you can use the sparse option:

Ahhh, is that was `sparse` is for?  Cool, that saves me a step.  :-)

> New release 0.16.0 has been published.

Whoooo!  Even better!  Thanks much!!!

I poked the library I needed but for now I'm overriding their cargo choice and it seems to work fine, thanks much!  :-)

**Pull request merged**
